stages:
  - quality
  - build
  - deploy

cache:
  key: 'cache-historico2'
  paths:
  - node_modules/

quality_job:
  image: registry.es.gov.br/espm/infraestrutura/containers/sonar-scanner:3.3.0.1492
  stage: quality  
  script:
   - npm install
   - sonar-scanner

build_job:
  stage: build
  image: docker:stable

  services:
    - docker:dind
  only:
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
   
deploy_job:
  stage: deploy
  image: registry.es.gov.br/espm/infraestrutura/containers/node:10.15.3
  only:
    - tags
  script:
    - npm i upgrade-rancher
    - ./node_modules/.bin/upgrade-rancher --IMAGE $CI_REGISTRY_IMAGE:$CI_BUILD_TAG --SERVICE_ID 1s910
  dependencies:
    - build_job
